trigger:
  batch: true
  branches:
    include:
      - "main"
      - "DASD-10212"

variables:
- name: BuildPlatform
  value : 'any cpu'
- name: BuildConfiguration
  value: 'release'

resources:
  repositories:
    - repository: das-platform-building-blocks
      type: github
      name: SkillsFundingAgency/das-platform-building-blocks
      ref: refs/heads/DASD-10212
      endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- template: azure-pipelines-templates/deploy/stage/nuget-publish.yml@das-platform-building-blocks
